default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: test_api_development
test:
  <<: *default
  database: test_api_test

production:
  <<: *default
